version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: rpc_server/Dockerfile_server
    container_name: xmlrpc_server
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - xmlrpc_network
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: rpc_client/Dockerfile_client
    container_name: xmlrpc_client
    networks:
      - xmlrpc_network
    depends_on:
      - server

  db:
    image: postgres:13
    container_name: xmlrpc_db
    environment:
      POSTGRES_USER: xmlrpc_user
      POSTGRES_PASSWORD: sizam_open
      POSTGRES_DB: xmlrpc_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - xmlrpc_network

networks:
  xmlrpc_network:
    driver: bridge