version: '3.8'

services:
  db:
    image: postgres:13
    container_name: xmlrpc_db
    environment:
      POSTGRES_USER: xmlrpc_user
      POSTGRES_PASSWORD: sizam_open
      POSTGRES_DB: xmlrpc_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - xmlrpc_network

  backend:
    build:
      context: ./backend
    container_name: xmlrpc_backend
    environment:
      - DB_HOST=db
      - DB_USER=xmlrpc_user
      - DB_PASSWORD=secure_password
      - DB_NAME=xmlrpc_db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - xmlrpc_network

networks:
  xmlrpc_network:
    driver: bridge